use colored::Colorize;
use std::path::PathBuf;

use crate::models::ConfigMap;

fn global_core_config_path() -> PathBuf {
    dirs::home_dir()
        .expect("Could not determine home directory")
        .join(".truss")
        .join("core")
        .join("config.yaml")
}

fn domain_config_path(domain_name: &str) -> PathBuf {
    dirs::home_dir()
        .expect("Could not determine home directory")
        .join(".truss")
        .join("domains")
        .join(domain_name)
        .join("config.yaml")
}

fn project_config_path() -> PathBuf {
    PathBuf::from(".truss").join("config.yaml")
}

fn resolved_config_path() -> PathBuf {
    PathBuf::from(".truss").join("resolved-config.yaml")
}

pub fn run() {
    println!("{}", "truss resolve-config".bold());
    println!("{}", "─".repeat(40));

    // Level 1: Global core defaults
    let core_path = global_core_config_path();
    let mut resolved = match ConfigMap::load(&core_path) {
        Ok(c) => {
            if !c.0.is_empty() {
                println!("  {} core/config.yaml ({} keys)", "✓".green(), c.0.len());
            } else {
                println!("  {} core/config.yaml (empty/missing)", "·".dimmed(), );
            }
            c
        }
        Err(e) => {
            eprintln!("  {} core config: {}", "✗".red(), e);
            ConfigMap::default()
        }
    };

    // Level 2: Project config (read it early to find domain name)
    let project_path = project_config_path();
    let project_config = match ConfigMap::load(&project_path) {
        Ok(c) => {
            if !c.0.is_empty() {
                println!("  {} .truss/config.yaml ({} keys)", "✓".green(), c.0.len());
            } else {
                println!("  {} .truss/config.yaml (empty/missing)", "·".dimmed());
            }
            c
        }
        Err(e) => {
            eprintln!("  {} project config: {}", "✗".red(), e);
            ConfigMap::default()
        }
    };

    // Determine active domain from project config
    let domain_name = project_config.get_str("domain");

    // Level 2: Domain defaults (if a domain is specified)
    if let Some(ref name) = domain_name {
        let dom_path = domain_config_path(name);
        match ConfigMap::load(&dom_path) {
            Ok(c) => {
                if !c.0.is_empty() {
                    println!("  {} domains/{}/config.yaml ({} keys)", "✓".green(), name, c.0.len());
                    resolved.merge(&c);
                } else {
                    println!("  {} domains/{}/config.yaml (no overrides)", "·".dimmed(), name);
                }
            }
            Err(e) => {
                eprintln!("  {} domain config for '{}': {}", "✗".red(), name, e);
            }
        }
    } else {
        println!("  {} no domain specified in project config", "·".dimmed());
    }

    // Level 3: Project overrides (merge last to win)
    resolved.merge(&project_config);

    // Write resolved config
    let output_path = resolved_config_path();
    match resolved.to_yaml() {
        Ok(yaml) => {
            let header = "# Auto-generated by truss resolve-config\n# Do not edit — re-run truss resolve-config to regenerate\n\n";
            let full_content = format!("{}{}", header, yaml);

            match std::fs::write(&output_path, &full_content) {
                Ok(_) => {
                    println!("\n{} Wrote {}", "✓".green(), output_path.display());
                }
                Err(e) => {
                    eprintln!("\n{} Failed to write {}: {}", "✗".red(), output_path.display(), e);
                    std::process::exit(1);
                }
            }

            // Print the resolved config
            println!("\n{}", "Resolved configuration:".bold());
            println!("{}", "─".repeat(40));
            for (key, value) in &resolved.0 {
                let display_val = match value {
                    serde_yaml::Value::String(s) => s.clone(),
                    serde_yaml::Value::Bool(b) => b.to_string(),
                    serde_yaml::Value::Number(n) => n.to_string(),
                    serde_yaml::Value::Null => "null".to_string(),
                    other => format!("{:?}", other),
                };
                println!("  {}: {}", key.cyan(), display_val);
            }
        }
        Err(e) => {
            eprintln!("{} Failed to serialize resolved config: {}", "✗".red(), e);
            std::process::exit(1);
        }
    }
}
