import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col items-center px-6 py-16">
      {/* Background gradient */}
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_center,_rgba(15,190,175,0.06)_0%,_transparent_70%)]" />

      <div className="relative z-10 w-full max-w-2xl">
        {/* Logo */}
        <div className="mb-12 text-center">
          <Link href="/" className="text-2xl font-bold tracking-tight">
            Link<span className="text-accent">Right</span>
          </Link>
        </div>

        {/* Content */}
        <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted">Last updated: April 2026</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-foreground/80">
          <section>
            <h2 className="text-base font-semibold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p className="mt-2">
              By accessing or using LinkRight, you agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not
              use the service. We reserve the right to update these terms at any
              time, and your continued use of LinkRight constitutes acceptance of
              any changes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              2. Description of Service
            </h2>
            <p className="mt-2">
              LinkRight is an AI-powered resume optimization tool that helps
              professionals tailor their resumes to specific job descriptions. The
              service analyzes job postings and generates ATS-optimized,
              role-specific resumes using artificial intelligence.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              3. User Accounts
            </h2>
            <p className="mt-2">
              LinkRight uses Google OAuth for authentication. By signing in, you
              authorize us to access your basic Google profile information (name
              and email address). You are responsible for maintaining the security
              of your Google account and for all activity that occurs under your
              LinkRight account.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              4. Intellectual Property
            </h2>
            <p className="mt-2">
              You retain full ownership of all content you provide to LinkRight,
              including your career history, resume text, and any other personal
              data. Resumes generated by the service are yours to use without
              restriction. The LinkRight platform, branding, and underlying
              technology remain the property of LinkRight.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              5. Limitation of Liability
            </h2>
            <p className="mt-2">
              LinkRight is provided &ldquo;as is&rdquo; without warranties of any
              kind. We do not guarantee that AI-generated resumes will result in
              job interviews or offers. To the maximum extent permitted by law,
              LinkRight shall not be liable for any indirect, incidental, or
              consequential damages arising from use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground">
              6. Contact
            </h2>
            <p className="mt-2">
              For questions about these terms, email{" "}
              <a
                href="mailto:support@linkright.in"
                className="text-accent underline underline-offset-2 transition-colors hover:text-accent/80"
              >
                support@linkright.in
              </a>
              .
            </p>
          </section>
        </div>

        {/* Back link */}
        <div className="mt-12 border-t border-border pt-8">
          <Link
            href="/"
            className="text-sm text-muted transition-colors hover:text-foreground"
          >
            &larr; Back to home
          </Link>
        </div>
      </div>
    </div>
  );
}
