"""Resume → interview practice — Pillar 1 ↔ Pillar 3 bridge MVP.

Reads `<run>/artifacts/15b_interview_prep.json` (generated by step_14 via
NEW-6 deterministic + LLM-fallback signal classifier) and walks the user
through per-bullet practice:
  - Display the bullet
  - Show the competency signal it conveys
  - Show 2 recruiter screening questions this bullet best answers
  - Show the STAR seed template (Action pre-filled from the bullet)
  - User types their answer (optional)

No LLM critique in v1 — that's a v2 add (LLM rates user's STAR answer).

Per Jane 2026-05-02 (memory feedback_bullets_sell_fit_and_seed_stories):
"every bullet must serve as baseline narrative for Round 1 / HR screening
rounds for common questions that are always asked always". This command
operationalizes that — each bullet → narrate-able story for screening.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from linkright.config import LINKRIGHT_HOME

RUNS_ROOT = LINKRIGHT_HOME / "runs"


def run_practice(run_id: Optional[str] = None,
                 interactive: bool = True) -> dict:
    """Walk through interview-prep data per bullet. See module docstring."""
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table

    if not run_id:
        candidates = [d for d in RUNS_ROOT.iterdir()
                      if d.is_dir() and not d.name.startswith("hyp_")]
        if not candidates:
            return {"error": "no runs found"}
        run_dir = max(candidates, key=lambda p: p.stat().st_mtime)
    else:
        run_dir = RUNS_ROOT / run_id
    if not run_dir.exists():
        return {"error": f"run not found: {run_dir}"}

    ip_path = run_dir / "artifacts" / "15b_interview_prep.json"
    if not ip_path.exists():
        return {"error": (f"missing {ip_path.name} — run "
                          f"`linkright resume tailor` first to generate it")}

    payload = json.loads(ip_path.read_text())
    console = Console()

    summary = payload.get("summary", {})
    total = summary.get("total_bullets", 0)
    sig_dist = summary.get("signal_distribution", {})

    console.print()
    console.print(Panel.fit(
        f"[bold cyan]🎤 Resume → Interview Practice[/]\n"
        f"[dim]Run: {run_dir.name}[/]\n"
        f"Each bullet on your resume tells a story. This command walks you\n"
        f"through which competency each bullet signals + the recruiter\n"
        f"questions it best answers + a STAR-format seed for your narrative.\n"
        f"[dim]Resolved via: {summary.get('regex_resolved',0)} regex / "
        f"{summary.get('llm_resolved',0)} LLM fallback[/]",
        border_style="cyan",
    ))

    # Signal distribution overview
    sig_table = Table(title="Your Resume's Signal Coverage", show_header=True,
                      header_style="cyan")
    sig_table.add_column("Signal")
    sig_table.add_column("# Bullets", justify="right")
    sig_table.add_column("Bar")
    for sig, count in sorted(sig_dist.items(), key=lambda x: -x[1]):
        bar = "█" * count
        sig_table.add_row(sig, str(count), bar)
    console.print(sig_table)

    by_company = payload.get("bullets_by_company") or {}
    if not by_company:
        console.print("[yellow]No bullets in interview-prep payload.[/]")
        return {"total": 0, "walked": 0}

    if not interactive:
        # Non-interactive: full dump
        for co_name, rows in by_company.items():
            console.print(f"\n[bold]── {co_name} ──[/]")
            for r in rows:
                _render_bullet_card(console, r)
        return {"total": total, "walked": total}

    import questionary
    walked = 0
    answered = 0
    user_log: list[dict] = []

    # Per-company walk
    for co_name, rows in by_company.items():
        console.print(f"\n[bold cyan]── {co_name} ──[/]")
        for i, r in enumerate(rows, 1):
            _render_bullet_card(console, r, idx=f"{i} of {len(rows)}")
            try:
                pick = questionary.select(
                    "What now?",
                    choices=[
                        "✏️  Practice — type my STAR answer",
                        "⏭  Skip this bullet",
                        "🛑 Stop — exit practice",
                    ],
                ).ask()
            except KeyboardInterrupt:
                console.print("[red]Aborted by user.[/]")
                break
            if pick is None or pick.startswith("🛑"):
                console.print("[dim]Exiting practice.[/]")
                break
            walked += 1
            if pick.startswith("⏭"):
                continue
            try:
                ans = questionary.text(
                    "Your STAR answer (one paragraph):",
                    multiline=True,
                ).ask()
            except KeyboardInterrupt:
                break
            if ans and ans.strip():
                user_log.append({
                    "company": co_name,
                    "bullet": r.get("text"),
                    "signal": r.get("signal"),
                    "user_answer": ans.strip(),
                })
                answered += 1
                console.print(f"  [green]✓ saved your answer "
                              f"({len(ans.split())} words)[/]")
        else:
            continue
        break  # exit outer loop too if inner broke via 🛑

    # Persist user-typed answers
    if user_log:
        log_path = run_dir / "artifacts" / "15c_practice_log.json"
        log_path.write_text(json.dumps({
            "run_id": run_dir.name,
            "answered": answered,
            "walked": walked,
            "answers": user_log,
        }, indent=2))
        console.print(f"\n[green]✓ Practice log saved to {log_path.name}[/]")
        console.print(f"  walked={walked}, answered={answered}, total={total}")
    else:
        console.print(f"\n[dim]No answers typed. walked={walked}/{total}.[/]")

    return {"total": total, "walked": walked, "answered": answered}


def _render_bullet_card(console, row: dict, idx: str = "") -> None:
    """Rich-render a single bullet's interview-prep card."""
    from rich.panel import Panel
    sig = row.get("signal", "?")
    rat = row.get("signal_rationale", "")
    via = row.get("resolved_via", "regex")
    text = row.get("text", "")
    qs = row.get("common_screening_questions", [])
    star = row.get("star_seed_template", "")

    via_marker = "🤖" if via == "llm" else "⚡"
    header = f"[bold]Bullet{f' {idx}' if idx else ''}[/]  {via_marker}  [cyan]{sig}[/]"
    body = (
        f"[bold]Bullet:[/]      {text}\n"
        f"[bold]Why it sells:[/] [dim]{rat}[/]\n\n"
        f"[bold]Likely recruiter screening Qs:[/]\n"
        + "\n".join(f"  • {q}" for q in qs)
        + (f"\n\n[bold]STAR seed (Action pre-filled):[/]\n[dim]{star}[/]"
           if star else "")
    )
    console.print(Panel(body, title=header, border_style="cyan",
                        title_align="left"))
